apiVersion: v1
kind: Secret
metadata:
    name: ziftbook-mailgun
    namespace: ziftbook-prod
stringData:
    api-key: ENC[AES256_GCM,data:o85vzbjbJ6KwmRVcfzC42rzAzMkuUvdnhLCF+qklPSEjqE1togrSKjtwEhqwBhBoB/M=,iv:RVWI8TXFAJyLMRiZunbjcGpDjkiuKurAq7pt3/Bc/aI=,tag:a0PiW5+68jcywkIlw3xJQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzckFrMEV3UEF5WUNwME1p
            YlpKTlVtajNrYjRTNThId2NwcUxLOUJlNTE0Cmo2UGtvdEhEWG12Q0tuVnJnTE5T
            RTFWNnk3bWg0TlQrVzVnL25rSXpSWW8KLS0tIFljTXVscjR2ekJJbndqOXlOMlVI
            VmhHTkMzbUluY0QveFJpNC93ZVlIMlEKRl0v6WmzZcps7VMDS/UsQZGD3n2nm0Tp
            BeUDmJlSmPL45rV90jjVXcR0R4/oeI/jWMClO4poqrLCFKg0G/PS/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T17:18:21Z"
    mac: ENC[AES256_GCM,data:q3Uzlv98M2A2iMd9J+/g9yFBC1S5W7beOkWmXMbPpMn4KEi6oLWOBI4+T2oqb+up0nlgzMI1Dt9wRd1q37zqXlKQvgZXcphVLsthyjEq1hOKDnN6+m7Vsxd9v0ikEnwiaeHbrIspg65HhnsBtq9RC0wWbYRZI9+cBvMylpOFgYg=,iv:TNnmkl+01GRPsspyDBGGHQrrqFcfkWpB3oYDU72hHa0=,tag:43k1Yi0mC0ltArq4L0ga3w==,type:str]
    version: 3.13.3
