apiVersion: v1
kind: Secret
metadata:
    name: ziftbook
    namespace: ziftbook-prod
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:Nu8m/mZs+Nkxdmh5kHRm9zpLus6IoMFoDUEtocgGdVE1KWNN0kryLqr+YJfurXOEGQ6wsKBIn8D5/Vqfuj5X6v2mD/orduX/xsbkaILr2KyaIeZL53FjEEFA+J6+BtxLAnh03Vp21rwRhcPObg8qrLVy4wFKsXzuPQHqSn2niWc5WujnPzyXmJfla0zLDF4q3mCvA5riEFOKPw==,iv:iuRifhR4aZqSa7+b+9fp0nPi7L1XP+MAA0KMgtR9Ys0=,tag:a9+/B0zQ86oHDDN8dLO6GQ==,type:str]
    migrate-database-url: ENC[AES256_GCM,data:qzxZQQGoB2mM3v6pRWNqi5LwsQZ6Z5kOrDruoSHz18vssDk4xe0wyqeItwmqyNKSJALuriqJ4MOoqiRACpxkVxLWRjExylK55XR1s0YkyzSh7JS6niIXoEdNNtoV6vnMFgkscR6phx+lRSM2DopHTS/qLgHdoTak+VZDqH9+2RRuNqZO9byx5Ol6XYd0LGPEWKr9u2vPFVqSGb5CfO0=,iv:4ZOG0jSSO0C0MTVy3fSu2nu74i0On7uvxSO+jfjP0jQ=,tag:VXkZZpct02WQ2ImKxeRvrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdHM2MjFEM05PWnpKWkVW
            OW1XS0grMXFsMXdaRVlFemxTWU5sTDZBT0RVCjlTV3NBVVg2enBnd2psZjJPWmVP
            cTJRMHRJemY5RnkwUVFESXZVMkV3T2MKLS0tIHc3LzJrZVUzaVd2QnQ0cDZHTE9a
            NnRjN2hBbzROdFZDdVhwNlp6MTRTQzQKpIK8LSwuspWiWkat0bBxfeocWbTRA1C8
            BuR7jQBZcnG+tr5jx5PlNJ883q5p9+LtLjpq+9VhSNkXKxbLRQbHUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T15:16:34Z"
    mac: ENC[AES256_GCM,data:9Th018x2aQqd3Q/ZlgzmETTRoEpCzm/0EvPhITmHVn10PRo904ZP1OLVklTaVwF4aaXGP41or3+hV7AG+C6rrkOaOQvO3TvMiFE6k6k81Dhwf/s8j6qZlNlF0S5HnIlO+kNVQkXSV4ziV7mgEvhuw+huJ2UGWpwW/KnsKL93RTo=,iv:RxuTeyQNG5dXgmlBLXPZbtodCUdAFpdangL8t2vZIOQ=,tag:xmO7XXPnWte3N7UC/EJpkg==,type:str]
    version: 3.13.3
