apiVersion: v1
data:
    instance-id: ENC[AES256_GCM,data:fDkEebSHEhplhl/b,iv:5lFfvc6sfC+uTo6hmW1/dFqCmqjQvKl+BAQfnUb/qKw=,tag:Gda9HH+DZQzloxDKy6Q0Ew==,type:str]
    otlp-endpoint: ENC[AES256_GCM,data:MrMez/3gh8lIH9bMTvhm+Lg3DV9730c0AKRq03I8hhxIIUhZiNc4nkbW8ocV1/Eg7y3jw0fn8SF8EyOk/Xewq5/fuDqjunor,iv:Cme7j5RrDZt4PMjGSo3XP6Xu3VT7xiaAEt83gbjRSHI=,tag:AkHJhzHY+zRBk1Vc0VGHMQ==,type:str]
    token: ENC[AES256_GCM,data:3bEWvWy6rCMeuVyH6PIy46nb3pAnKi5bToeUXBHCnIsfN9XZu7/0ak+64QcY4qz00+ZMwLaAnAbvpo6CDTBbR9k12/becSSFsu7VfZrXt1OyDz7Ei+qz7GFZWJEUrdDfa9EA/Xm+uSMHfhJaBu3VYUWWXrd0Wj8opKy9sTOo7XtUqzKTPBsuJJ9hXc7+u7uOT7v0RfrEASamBkFpLshFc0OzYfa4qZpKU67Q59XENLUx9Wg++++mr8/Va49Crn8yu2z5Hm+lfH7cap+mz+KF5vuQAuWKMEht6Ncg/rd9BeM=,iv:+MhVIfqhokj+F5SnNldwcpdk9qnrDGzpaFcNLvyOT9s=,tag:55TB7WNFcL1pQM5lcy1wfA==,type:str]
kind: Secret
metadata:
    name: grafana-cloud
    namespace: observability
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZ1hRY2MxZkR6UG81Rytp
            VzkxS1lnMGtOU1FxdEx5VnVxWTNoaFNjdUF3CjZOOXl5cHByTjBmWHovZlFaOWxI
            bTNtOWZwdEZTRWxNOHR5L3BXOFFQZWMKLS0tIERCZzAwN3hkdDFGOXlXd2dXcmkv
            K3pZTXhoVEsyYkdJYVRXSUR3eDZ3YkEKp22egYZyt5iQ6yp3LPN1wKMFCEz1Fn7L
            1JjYn8apyLB5CzMBnitlx4DT1uEhz21ZncSosaUO2DDXKQFJha1grg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:57:32Z"
    mac: ENC[AES256_GCM,data:eJSio+9f43hG3OgHLEd2qrnk7oPKDp0X5xuLu4O3OzJ51zzueQCMmPfa1DvdVwBxqvBbrOjEwuBDPd11urIUlV/6LlcROHnN/EvWMXaMulS6f0/mHHdr6oaITgRupFMLa9tqW+i2rpi1UiMFm4yqPWPcQHSwy139gxqS+WLNYrY=,iv:r2RBfcqj0EhRnuDG9ybQIv0iq8+CR8LFuKiSBK9YjtQ=,tag:GXcWadSs6BogpTEBmNPWSA==,type:str]
    version: 3.13.3
