apiVersion: v1
kind: Secret
metadata:
    name: ziftbook
    namespace: ziftbook-staging
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:G+TePBLNfhIErIu41x699YkPMlqLqeAkLm9NqN9oBY92ZH3xq6S1Owt+/deKYnJs3B+LEWiIDdoYnqmvEmNZwu5VopuZ1Ykr1EKPD68x2GpPqGuetiQnA/gbjKxuJ3kuDERPUt1CDQJMedBuxVGbPf4pWldZhZulnrLLiAPkhHU=,iv:THyjnU6z0kLDN3fblVnFDH0t/IpXEiDjQAdwVJd9jvk=,tag:AHa47Sz6fxJUOWlnp+eeNQ==,type:str]
    migrate-database-url: ENC[AES256_GCM,data:2atspoKzseuey43hMFGrPsDciZgzZYcZ2WMeO9NN3XLZZ1gLtPGsxP2nnO+L64/GCuLWC8UlGrHPU3PUKFSoV2DMQ6R7nI135cmFW4P6oMJ1OUafEBh15ogP4xpyYTDdajvpMR03sA0l31bvxb+UbsJCMT2g4JGi3yR7YVfX7432Ve9H,iv:bavlmo0orJOrQxPhyZIlsXvIjT6k1WH6orp/r6hANF4=,tag:AD0JCLlh2dPjwc7AAcqFpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZUVDWWEyM1hybXR3dGNr
            N3lkR1dZMWlUU1pqRVQ1OEU4bUZPWmxYS1ZJCmNFRHlLMk1MU3JocW81STdXVG5h
            eHluKzZLRE9RbER5YS9tS01jeG4zaWsKLS0tIDJveGNOOXNvVk1lZEJ0WEYxY1pp
            VzJ0RlFqWitoZXlnZWVhd3NaSWFhRDQK1vG5jXgiCG2I+YCja0zTdOfTYVx2ETG5
            aUnS3w/0zK8UamXfvznngAFS2Nq8LyuqlDtzqS/1VVXVyumRzOLJXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T06:41:36Z"
    mac: ENC[AES256_GCM,data:ciQ0PUL6+xcG6xiJ5uaTHLV4UW/bCHaLJMuyOOdos5ihZF63ioLAcvA7/dIfhVsCbKhrXUq8IZoxM2unXdBeLXI96N0wpkdFTPISxlxfJUanPs9rLYV2I/r8sjPWm94oNJ+0KwxjEpTweBi6c7pWouaksNSw/J81xNf5v2HKqQU=,iv:FAjs0SET7NgM90BTNGNHEnaT2NO+Wpg09m5XNS0P31o=,tag:aeGh3OYZ+v9+kaX50YLfUA==,type:str]
    version: 3.13.3
