apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:hJN7UAtUjbM7qvTUFL36Uq5LHvylKqPE8pSjJvaLNDXiMe2b5Lzfbna7kCEMDV/qmd98LI+ADPrp2RQ2gaToLC8dr4I=,iv:A2kgf88pS3oE9dQ1Py9G4lHnICOBpcZ/uqku8dv2kow=,tag:2z50Dz55yVDF9V/30eM47g==,type:str]
kind: Secret
metadata:
    name: ziftbook-mailgun
    namespace: ziftbook-staging
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdmk2bDBKdGVmR201MXR6
            SHNOTnNuV21XQlkxVkNrNkNPVURZU3l3ekFnClk1QzdMYTJ4QTZ4QnpWb1U5cGRK
            U2U2ZWxVcjZqYWd0K3JiclF3UnNkQjQKLS0tIEdtVEtZVUJSYVo5V0FmZlBFbTlU
            ZFhjWTZ1U0k5ZHFMenZhQkwwTzJzazgKqz5wJ1S/IxoLJRAyGQnJnME/sF/SbxrD
            UdnLzYao/IOoAP1d0MF61bF2V/Krf0SH1b38pWKG87Y35qR2J1oeVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T18:50:37Z"
    mac: ENC[AES256_GCM,data:yaCx3h/Mzm+30mJdXq0TmJ3qruGippefPlUKTuLGtkuVz+HlolyziuAxwvNFvFPygy9nfUUmKKF6otMrkoz3XL69EGc1BUvzVvWuevj5ep9O5+IBMs6A4g2g/uNpqFYFTsvsJzHY6F78NjvXb+MZeQheBrqRDup0nt86LMztezQ=,iv:GJDFkWP+S1IQkua0pFJAVr8rIG5UtYEaGVtHu//rSLo=,tag:dyC3GwQxjvcQXO1pAx+hoQ==,type:str]
    version: 3.13.3
