apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:0y/aphe1BvRHAWoAwBC9+WClxovMvZJ5sZFQtP6ia47n02W6aKx47tkkZIXk2TBWU95LXUEKgqRqtgUmB9psPjJ35MI=,iv:d7ze5iRrQ7z4sErNBKbp4jc2WxoF0YJofdhO/UzHjf0=,tag:xgsYDOf2uH4271kZsK5imw==,type:str]
kind: Secret
metadata:
    name: ziftbook-mailgun
    namespace: ziftbook-staging
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRamZNcnQ4NER2dytVemhk
            YTFPVGlaOGswRk5ZaElTZ25xRlRPNFhiMXgwCmUyYXJpY2VuQnBPZXJhdnNiKzJs
            TStFdWN2QlNVdmd5ZHB4V0FlQUxoRGMKLS0tIEx6NDNreElmK1FjZ2RhaTA5OS9J
            T2NvNC9QSzh1YUcvTzFlQ1A1dHk3MUEKnIczHd3ZhaXmaXUIK/bcte9YOmOfCIb5
            pvYsy3Ucr2QycESAw0kt3QWhKw7A9k5YIWlCnSu0hu6/rkhllSFVzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T12:18:28Z"
    mac: ENC[AES256_GCM,data:1tqgIDn+nP2g+UDvWX8oZbQ7dgNQ5Py02s2ofRmElBuh7OsKGEgMrtoJp90uCEJGcNcAeilFNLLtjVU/H6CWat1J01ERtsmsbGXB+RTWYCstz6sx4P85KOVsDefap9cuDXXwLqvictVcItwQsPa4DLeF2eDtutOh8nzUMjTVS1o=,iv:h9HGTG9a4ZStB8a33KYgWx/DreCHdB2i+4KPO1tL0hU=,tag:RQomPPsUu9XYnoeXSzCS3A==,type:str]
    version: 3.13.3
