apiVersion: v1
kind: Secret
metadata:
    name: tbd-smoke
    namespace: tbd-prod
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ynySD3uv5jgAhbiLHnhQE6cztNkT1A==,iv:6SYWByBk1PaVMBYYvlydxfMl/JrPAEwyrSjHo1B3qY0=,tag:E9HOEVbhBCcoH5QjtMxYOA==,type:str]
    password: ENC[AES256_GCM,data:3uNKCZzVtnaGy3uj5UVNnNkiz4erefc/gvzgD5g7XaKk7dxAMpa2BDBjkg==,iv:qiCM6IvMUg1TbFY2Br5ppNPl/sdM+8QbTd3wT5EELyc=,tag:ih8obuwGBikEjjV8xhWP+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNblNTZVJ1ZmFHaWNNL2FJ
            M1FlakdnTFllZmFqUHdrazZUQXFKUW1Ibm5vClBmWklpN3lWV2lNMDI1b3c1VG5p
            czlEanI5UHBkOVhiQzdJeDNuK25DcDAKLS0tIDRIQXgwRFhhOGkxeU9oNDBCNUtZ
            U2RqRmFLR2IwM3daWUliNStMeGtrUkkKybV83Gq8d9l6fuO2oNJrsasWDwLQpUPp
            c7k7/bXOJkG6ITE+SdyxYr/tvjZ/gFFrIfuO52oqldsxa4J/AUKziQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T09:27:32Z"
    mac: ENC[AES256_GCM,data:zrDqVuQCmodRAmvgvF3hNnB0Zi9vDyVsc1a+N1Ddox4bOLFxYQ+9S+Y3FIrlTF67rP6RZUnLpO0BmSPWI/4zYAyeEn6DavaXKVjNcQU+HVOgOh/VGnudnhKPTtCO8oeK20W2sVKn5WEcNm+kXHCuVBzcjrRQaylykHV9nH6VOKM=,iv:VvkaAPzi5DzhSUMYmvCZ03Jmcu04UcTy8inhdD06h8I=,tag:zKaBPNFDcKmZ7eXysaNppw==,type:str]
    version: 3.13.3
