apiVersion: v1
kind: Secret
metadata:
    name: tbd
    namespace: tbd-prod
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:nbTPW7ljZEKRZWR8rBDQEYAOIA9H2e5rbJisXACt46ioLAVguBlyDZ2dT1pmgI4ceoUU8C09mJuLwTE8cT4bhVUkW902lJaIe19zp0KgN7Wpl2+D7dP84b2Z7uxvGhrBVErhAuvnCqw7FyV5oan6,iv:A2JPQgSzWCztEHqQLDM/MTnvYbkIPWODVog6KpnwLr4=,tag:WMhj+Z4tGSL/m8CGwXWAaA==,type:str]
    redis-url: ENC[AES256_GCM,data:edyReHPmnUeqwI/yUwq/vnSkDEllRUDw2WRKLQNe57q4GILOhp/5zV8heXp4cP7CApGzSSx1Fchd+YB5FHWAMTbFEH4uYyI7ylpQ6REr/iYaXzU9l3YNFbgEE448RsmblIGlXyK25bWqfAETVlk=,iv:6z30ZyN3NbIfwpaYmFjCXusi3BSSOn1deRicj6sJ1nY=,tag:6eWYBi5Ib62orY4L3W2vdA==,type:str]
    jwt-secret-key: ENC[AES256_GCM,data:Vl2GkIJySq7rvabidCYpjbHjpIsIy1PP6u5yhWXxa4CjiSYu2xDjGguc2jO13N/W5Ib7EH19Y9p+RcWVZLuhvw==,iv:InYS7yOI3RaGK2H5Dj5jr+DZpjo3ld0/3BjdbdYLLYM=,tag:+YAipdxuznUPi7/DSmhhuw==,type:str]
    mfa-encryption-key: ENC[AES256_GCM,data:3Jf2vvsJTWt49Tu0iGpaCywiAFSU5R48kf1DwRscrCbUYRlHmWfcggIIe4k=,iv:mjCGRmxHGwAYcp4rPFbfwh3YgGX4EqWQ+F+r+J7X9s0=,tag:Jrr+bibHNKCUk2gMGXpZBw==,type:str]
    ai-credential-encryption-key: ENC[AES256_GCM,data:83PTUAOxpB4pjHDTVD+8jbl6d2/KIHBczY6BRYJ54daAQbK2mClgPjDEoWQ=,iv:Ag3wAuj6+Aj9QNuAsOpXxQVIFuRVRfwKC4GWOKXZ9Gs=,tag:eBkatCreq26qKZGIW6vFUA==,type:str]
    ai-credential-encryption-key-prev: ENC[AES256_GCM,data:WSSFjV6Uh3KuJlhtVcRjKXQ9OKvvCNK8WDpeeCJzUN87qdHQXlc0iNWjDpY=,iv:cHA83BzT4cuRolMBlYO8F+hJ6EYygWVXhV/5Ez9BZeY=,tag:7+9LwFLpgy/SV5dYs+3AqQ==,type:str]
    api-token-hmac-key: ENC[AES256_GCM,data:zI/QtyeuOZbOHxQJpV7bTjXu/WCegEi+dXwWSivV1UY6luzaci9htInq27gnZIF5w7iKA4TN7zkDhVsmLZRPqofVMeyKnMH2LqSLrQzeDcFx4z2nAF0=,iv:Mjwb+v30OwHTCOYmM96/cyu2gEJZOkSMGIDk013NLwQ=,tag:fny/RO6cO1aTroUByCq8YA==,type:str]
    mailgun-api-key: ENC[AES256_GCM,data:/ialyHIUSEQiJRCFYKWLRmKqKsJbkGsKxzjuWbjFRo0XMCpodXUH+h43FX8NAaMAzs0=,iv:b+/XaS1nIzumUjluGn5W6eUlkhSyooIKcyT0N5boMXM=,tag:zVMcK91WaS3aA3j4SlVGAg==,type:str]
    mailgun-webhook-signing-key: ENC[AES256_GCM,data:kID3TncZDDyVn2dOa3i9BQpMEhXePitChSGfEQ4WJNdvg9Xg35oUeJeu2xvmqsKU9s0=,iv:WUOUsjVAQqPFHp80b/lrt4pnVkWUEjJ1dAkBAf4z/NU=,tag:lD21mB35xayCE+qGdzg/eQ==,type:str]
    google-client-id: ENC[AES256_GCM,data:VYe0CtqgCwG/ENMzH6nMuTZjFliJekAjS0pz2DDZj6CMILR5jI5HEMAOiaRyqK47bos3g0AzTdiwky6s9RJJGMd+P2tMjXZN,iv:J4ur7jisqx4BwCIuuEhs6nAvCa2PsN7SySeQeNsWGbE=,tag:cKYKh9z6V4LzrlYkNDaYLg==,type:str]
    google-client-secret: ENC[AES256_GCM,data:IeCqk4FYauXNI1TfEC+UO1fCuw6sQilU6QKqFGygbKnRXDg=,iv:fXSgf2/JUeh38DsFHPFalPdDyi3Y25sx76GatvixXYA=,tag:2yEA5vCfE3YlrTDEyFj+/Q==,type:str]
    captcha-secret: ENC[AES256_GCM,data:FNr9uFXDLFaoeTFPa756thPQ9Qr4Mj0okvGtxclTGinhXF4=,iv:N6q99yfqhAs3Vify1iRbMgIAgs8IGUf6SzrCRplILUc=,tag:iMNlTg3Cphm7y2Yfs3JxfQ==,type:str]
    founder-count-exclude-usernames: ENC[AES256_GCM,data:F4htXm/wpowOwouXXyP3oFpmO3wRLA==,iv:HgCFWqIMV4FdxAPxdj/v0mnhLKLd9hhOrjdorhOTox4=,tag:Swx2cZYn5aa7na44dU4DQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQb09NVDRCaXZtREQvZERt
            K0RtVjNyeHFzOTYyc0pNUzZTbmg4WjA2SlJZCm1Vc3o0cDNYeUpVRmJnVWtlSHkw
            WisyZkV2Qk9na1Fyb1RHdXBraFJBODAKLS0tIHFhUjd6dWFxWWEwMFFFWkhFeHFX
            YThFZXlienVxb21URlZSdkM1a2tjd0UKds7ZEM7B5hMrZD8dXJh+skoUEkwOy4QR
            ej15K32I9iSlJFi4zYMzwwS04LqG4Wh+q6Ryd+Bxieu2KAvAbj/dyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T09:10:24Z"
    mac: ENC[AES256_GCM,data:l8aNBJ8e1UXJImb9qyxSrSU7bzvuZGYjb6pCUzJAFioX6cRGLRClq5UkZ9MTjkMyodGfX3bNrSsNSL4duq0B+1XQ+j/de8Su+noOj9HS5SLGiQa1lUQWMX7F2b4TOFA6Ec0nux1gLObDabNsLZ3m3pwIGPnFpnP/VCU8FlIr63k=,iv:DoQ03xLXE+2v4YY79EON3Ws3BPgmpckh1xYhZnchEB0=,tag:WICl5tTJ4WOILefNxw0gGA==,type:str]
    version: 3.13.3
