apiVersion: v1
data:
    jwt-secret-key: ENC[AES256_GCM,data:T1PlRbimefauYT2CrO4zMx7hGuO17ebNHHI8ASJ+URCZ/D7PmpFFIr4bAom50GnQC+B+dWq/SfJVZ2fj/h2WYiOPTWYEAFZSbspu8KUjXK0P3E6CWK2i2w==,iv:Cm667O1jpAhHy8INYNc39awADWiXJt8K79n4fN9xp5g=,tag:+j1rH8WbLcxCbsE3xC9nNA==,type:str]
kind: Secret
metadata:
    name: tbd-mcp
    namespace: tbd-staging
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ3N0cFlKbGVET25oK1pT
            VnRJc1llRUlGd3kvc0IrVm9kYWF5RStDMkg4CjBMRE1BOHEydSs4VzNnOWFCb1Jt
            QkwyalNzampPZytYL1cyQjlFNFBueVUKLS0tIHZCY3pZQStQZ002U01OL0FSVnV1
            WFcwWHM1Y0tCeW1tdHZmVkREWnJBTFEK7k1pZzzZYy6uj624iZepRSItLQcxuZNb
            X6TJN6j4VFeXEpL0SGbYi4CnOTqzVLrQOcO/NNhbjc0cr8n82SbN2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T14:45:02Z"
    mac: ENC[AES256_GCM,data:od4v4nOc3BmU3uWSQgy1Q9WBAkNZWrWIur3BoqOIwMQX7m+GdinwgCd5zFu5Cb3N81BJixbgzUjB2M406M6lmEGXXFdyc5ACT6285rI4fdx2YCvMgzvVN+BhE4U8Zwt7O9kIJcZ5lvrDSI6Qua4EWJ+HR696f8LOiWkE4Z8hoo0=,iv:jt+iiZ3KMIL2xHW/AlWgKHIlwMbLKj8FD9Im1XWZSW8=,tag:EEzPZg9B4dxcY7jqMJCe9Q==,type:str]
    version: 3.13.3
