apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: tbd-mailgun
    namespace: tbd-staging
stringData:
    api-key: ENC[AES256_GCM,data:fdN5MOMxzBPENqFrciFp3enmiTOsLd06AyzzvMnJceM+5aua7vvD0SPAeFNhH+50oeA=,iv:YBJ4TiKhJGDdOwxYNrO2rB3swZQ1UvGte/3lVNlgxyk=,tag:dYj+r2NMMTKf/d7kFUibHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeW03czQ5emZWTWZMR2dK
            RkM2VFVIc2N4dVhLU0l4UnNrVUhaTUd2TWxNCmNBekZpVm9HWHVneDlsNG1IckpQ
            aUp5WWk0aDdnU1F0Y1drYTQ4WUwrb2MKLS0tIEJIZDJaZHQxS3FTdnRXdTZnVnB5
            cjh2MkdVK2JRNHJqdU9aVmVLRk1OejgKbx3xaWsij126RgjiQU9D5NP4/XMaiFry
            JlHUdIEYgLEf+Gkp0ARup68uI0FAAYjFcuS1VYk9TkZDJ/V379+QKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T17:04:31Z"
    mac: ENC[AES256_GCM,data:6pLAzyTGfhDc3bhx13BQmLWLN4Cqn7hqaS4oRPmhFzPsAU1s8flAX2oSmYtv8dnk93JtS7hXfV4YK4G6Ssf/WeJz7urae+3QTHMb/lDVBARbwaxm91xsWkIzNRu3P0vSL1FvtuKGUVh1nq5/Ga5tm/g/YvrwkK+ozSY3XMTqAq4=,iv:shpl3PrU2n0hA4I7+Ij7PqqgRoTZSXF9VHvcRjDmONU=,tag:rD7wMl72A5SAd/CGFBTi1g==,type:str]
    version: 3.13.3
