apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: tbd-captcha
    namespace: tbd-staging
stringData:
    site-key: ENC[AES256_GCM,data:69SSZu34qmnrLtlAHL81VFRGYYdsN6ZF,iv:gWp2oHgio2dxzoS5s3bJZ7fW56z8BdtvIf29Vj4XfpU=,tag:XH+iyHbdBvblyWDjVl9+ZQ==,type:str]
    secret: ENC[AES256_GCM,data:nNXfZe5uYgpez5E1sYkoAXWF/2juEBL8eu04xWRuj0+oacw=,iv:HoIXkQyc+McHt8Yoe64l73wCnpCeoHBk1Ex8If3lKVA=,tag:Zx9vxScU1dFwthBqAW0nzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQM2hZcFJTUjB3d3lXZEJh
            Tk9uVndHSk92MHdMQ0xEeVlLVjlNSUVRbEg0ClU5TGU1anArWmJBUmxGaVJnbE0v
            YnJtN0RZZy9leWovOU85NVFZUVpXenMKLS0tIHF4bStiVngvcnZFTHNyWmhLbW9s
            NkJNanVnSXUwQ2tuUUhEU1N3aWY5dDgK5zOaxwXLNCGmYb1JP0i/hWCv95xW2d6I
            vba7CUdRnzhQL9LesMKQZffrA990O0nHRy6JCZVFu5O5vex0EmxxPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T10:38:46Z"
    mac: ENC[AES256_GCM,data:8EzSQoBBVJI9BxABRPB/lyQkVE3djNmNKSkoUSuj3usZkiy+aFaXLpzCTtFcPrWFOVhtXIifBU5M/nub1v/EzzULMn9wk6dgKlngZ5SU+mT5wF7j58RUl4BLc7jif4TGX2ryBVoro61Ug57Jv/q48xtOFwyUDlMT4U56sb5bygw=,iv:DCak3k7hsRFrgCLwxa1Dx7rK26coY1HPx6eB16D0j2Q=,tag:HVjEyTYi0K09HwfKQezMNg==,type:str]
    version: 3.13.3
