apiVersion: v1
kind: Secret
metadata:
    name: tbd
    namespace: tbd-staging
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:MivYSi5hw7bGMm4hdDvmWtzmGxAv/UeCMBOU18cRfgoVMwmTbURpzTOOi48v2uFDzIYd7Ecv68FSVi10Z6PWsMIM7/KcUis/s+OEUgwnnXdmp1hinBi+7HiJ6tb2bO5Cpkf/1twA3Usb+C+QlLY//gWsic7fYhpuH+SjvVoyps7tDqCk7tn66TjOnw==,iv:EI4/ZYAXBEOYT/ELRebtV25UzL9bFLr4z+OyWSGDJ5M=,tag:tLJXS3NC7OtvrBopAEWJ6Q==,type:str]
    redis-url: ENC[AES256_GCM,data:Th6uV905mm10WQWlO3XyMZNSV/kFREceH1eafdDO/go03IfaNFUT0/PgJczJeIw4rL2Bh9Eev0x+ZQ/CQk6PRRrMdVvLV1ZbqV5z4PE6F4msleeOAGP+,iv:gHROR6nY/51wJQav/lZBFSFdrxDT6BZlxnbGDCrHXQ8=,tag:y3YG5AWq443DT/WxswT7pw==,type:str]
    valkey-password: ENC[AES256_GCM,data:Dl/eDypl8+wolf2y3mYxOFPxQ/vkIOftnbnFXCFkveE8evDxpjHeyxrmuA3L6hVBwP5vs/mGZzdmJT6nLth5gg==,iv:hzkiHiCfotzCCZjKsLsxHrZR06HRekxIce9bhvtmHDA=,tag:ZkIPgDsPvuk/dNC6AnPPcw==,type:str]
    jwt-secret-key: ENC[AES256_GCM,data:oYDSXtzeUQD8wHe4LWf9cuyNR7IQbJKhGYvCJszR5XzjO3thu4zkDO192sz/0604aOHk/8CqgEoNQdcczH/5nw==,iv:t/flb5ec4kAYKXUs6E0Dpd0bZVjQP76Y9BPEbn4Re34=,tag:GoTi4NdUSEVZcntm0X4gSg==,type:str]
    api-token-hmac-key: ENC[AES256_GCM,data:OiF5Sn3+uMYGyZxOakuT7Gz7Y4gs4DHENwSO5Eu4PloJqt2jkCmam3PaIxGCDMTD2Zb8LZb6eBNVJubRkQ+vxQ==,iv:J4ONEHJn9HpGS+Ia5+ADLahCVtpAd2e78SrT99JDbDA=,tag:AdMvq3uUFqwqIaSf/7DBQQ==,type:str]
    mfa-encryption-key: ENC[AES256_GCM,data:GsQLkYLeb/EUkoK6uzgAnENyNasT1V2l8ADHrlGtKrL2Ni0Ee1mPM1I3yrs=,iv:weAFktBU1NL2ZP7oLUAIwYSq3WhZ49EcHgGdM67LWXs=,tag:A+ekNq9mPf6Zd3LHSlB5Lw==,type:str]
    ai-credential-encryption-key: ENC[AES256_GCM,data:h80mcMLBasHzp6Zc6V5LtJMRkKUcRZORytJLPbxM1u1u2+rlZq1yw8/SOYk=,iv:X8+7m+MwQmEP9s/LxIRpln2Bp5s/y7e80N7NxyaiNDo=,tag:DPoBqE4HWn+wuOkxgiQ6xg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTXRwZEZzQlZCVG9qMGp3
            ZEh4N25pZ1NCc1VyL1RtN0REcnJ1amxtUFdRCmNDTmw1YXp5ektTdWd6SjZHbFJx
            cXVMcDd1OHN1UU5xSzJmZThWU1NxZzQKLS0tIGdSa2tmWk9vcjdiaFVyOWh2ei9j
            Y1FLeXVYTG5qSlpMUGNHaVcwa3A0ekUKMu15CxwC8GjOEDvQ+Fu47NZLi9HO+Tpn
            g3emcZYdRhwcY1cSQFuV3gGmSt+1Tv8AU9f4xGomeXJXbwJeVk1IMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T15:25:10Z"
    mac: ENC[AES256_GCM,data:O3iKd5c0Z4+7aOZBtCusLKiBs/mTI9PH00aYZYzL+felYs5F+UcDYyj6X6tcXImilPD2tHnmulmkc8wgxZdVOh9Ka4X4aFvihSVAlwh0TD3FmncDaFfXbD2g/B4hcADTnL9ffF5NrI07VdE0ZW15iSotihQzxbgqO0oHa/kbHXQ=,iv:lCaDWcQg3wnKWlQUnKt72DZroXUv0iO7aLS1UDc0aoU=,tag:JMFcMYxUKXnMFNPkYHb43Q==,type:str]
    version: 3.13.3
