apiVersion: v1
data:
    NB_SETUP_KEY: ENC[AES256_GCM,data:NsJdK8eD4aGlybYc3r1zzwDDWfrPSYnKEV3i+XVsJUvijHHLf9HRw7Xs/aJpqdmY,iv:wkRYYCZddMQSc0WlImqny7di2RRP22AEFiw6Mw/wioA=,tag:lVjlUeDLkKb9mceHHrA8NQ==,type:str]
kind: Secret
metadata:
    name: netbird-setup-key
    namespace: netbird
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR1JrdU1MN2VJSDBIWXdr
            a1N5clFTK1pnbmtxVkM5NThVSjJra3daOHpzClMvRzJ3UHJRNlJZMHdDSzFNT2dt
            b2dPVHJ4bXJyVXVNY3hibXZRU1VLVnMKLS0tIDNuN0xiRVBhQWNFdDg1UTVkbGNV
            b1FyVktONTVyZWxZbWhkV0d2N29QVk0KRItAy/NETLsd383Pv7Ae3q4oQPZO1F1O
            Bfcy3kE0j0jyKV6Gtr8SLu1oTqUJ1ApPiiponKqquiuwzY/u2YaggQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T09:26:02Z"
    mac: ENC[AES256_GCM,data:/QT09ua6ftiBJV1oQwYaSo6NRtZvGwIiqpLfZUQnQzluCQCkQnLSE84Vw38bZVya76ROzT3nNWE787YrVJ6f+xhJxtFtTgv9le8pZhZk8r9w9bUKUc3bsXXUTrVF95ZG6RV28vyoTCTI4zPXTxModQcXuHCxsnoaXa/3hVZ/3UE=,iv:JfWyNFhMU5vMmzZH3UQMOlYyq6YB9fEHM2wmxZMPPeA=,tag:jcxgVpW7a+XXjo6H138Qig==,type:str]
    version: 3.13.3
