# Canary: if this Secret exists in-cluster with value "decrypted", SOPS decryption works.
apiVersion: v1
kind: Secret
metadata:
    name: sops-smoke
    namespace: flux-system
type: Opaque
stringData:
    canary: ENC[AES256_GCM,data:H8Ym0YLpsfgS,iv:x46otzfP0U9alJITTM0y99801AJzbaF1u5JCOfmHQwg=,tag:Sd5kwNk7EzS8s5HzyWJfvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeVdheGdkNk1qWFM2TFhO
            aDh2dzFDZzM1SkM0TGtWRG0ySldGdDJyUGo0CmVsT3B2dCtTeEJYQXdrTnFkMlhq
            THIybnErWVdINllEYWswYXBhSmtrbEkKLS0tIHN1cHUyZW1sZVhiTzczUnNsRjR5
            QnU1U1hoMk1MM2xJRkxWcndQOXlmSEUKArb8w0KwRRD1ENjT77Eb4S+JvDQyhPSq
            wc7fuab9ViCb98O+Zte/PVxEs71qHzd7DRYbQP+mV6xNHxmssY387Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mz9payf8pxgmsn6am82tv78dx3wfhyt5ak8ruhtxtk2emhrmh45qhmdls0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T06:24:45Z"
    mac: ENC[AES256_GCM,data:bpns+L1Z893av0eG3BP4qe8gg1EXdDTQsw06QPMy99kbnlXfvOcisNCBRL2Yiybm2U6JDtDsOUvsY/MEp+SDHzFgnAJyJdXjakfdobz65KrKhU5pYB69/Q1T8LrYAjnrN1DjY+SfpYm/4XHn8/T2X7KGiaLIJEdrfc65tgFm+Ys=,iv:+hjAUDzwOD7k3xrbJ/Z+YXu8th6ICunD5a9MLUt3PXA=,tag:Iw1cEmVahV5gBdxyiosb7g==,type:str]
    version: 3.13.3
