# Canary: if this Secret exists in-cluster with the value in stringData (changed on every key rotation), SOPS decryption works.
apiVersion: v1
kind: Secret
metadata:
    name: sops-smoke
    namespace: flux-system
type: Opaque
stringData:
    canary: ENC[AES256_GCM,data:QYB0Vfx1tPRx/hqKE8SDWSzp,iv:TORr9SJIgz67wFu5SZ1f+Lh4VKGvX0bmtVPeGBftD/8=,tag:yTSBNkmXpuJ5bHdj74Ww7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXLy9JaFIxK0lET1UwUm1m
            SS84WTgrdjJaQjZzQWV1MUFsamRqakhhRmdFCmNPQ1MwNU9lQWtOZUIzci9kRG5r
            QWxzbE1Xd2JHNmhhcU1OSnc4WGw4T2sKLS0tIGQ5Rm1SRUdoekRrM2laVityckZh
            UzZmK0F2akk0OTJ2Z0NQb0hXdS9ERTQK5b7v+a3K1WPeflAO5aHQP7qDxZyXXSC+
            fGr3OLniiayb44uNDYhPfNzOWVCkTeelOjZvBK/ktaX41IGUH7eZQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T07:11:54Z"
    mac: ENC[AES256_GCM,data:i7o1Ft4XjFcd/kKYh/FFEpvumdijbLFHCXQWFYXu36VdOYlph/NT2F+e5tJeH8ntRVkvi+Q76wl3pILcSRS1vRA8hCirXEnbu4q/28wv3UX7E6GwmHG7quSTdzpBwynGrSKsTz1aNcxgKtf3p6g9Slq8TA7srVbNVO6p6/Py4VI=,iv:CbFfenVO/rm/2Cqc9HI0b1aikQmObPG7Wg0viLbYIuU=,tag:rzLu0h5GGxS1pl688PbawQ==,type:str]
    version: 3.13.3
