# Canary: if this Secret exists in-cluster with value "decrypted", SOPS decryption works.
apiVersion: v1
kind: Secret
metadata:
    name: sops-smoke
    namespace: flux-system
type: Opaque
stringData:
    canary: ENC[AES256_GCM,data:k2P+8g//9igg,iv:x46otzfP0U9alJITTM0y99801AJzbaF1u5JCOfmHQwg=,tag:syvAytniZUHJhEpSx91YBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZStKM2pGbWJMenhGc2tr
            TUZRLzJzNlZhVWYyNEFMRmE1S2g2Z3NqQmw0CkQyWDFOVEhlMFBnTkp0QnlYZ1ht
            Z2JLRHpRcjB2REVUYU8zN0FCbVF5UXcKLS0tIHFrUy9idzZOdXgvVFFCQnVDUStt
            WFU1TFplTkJ6K2VzNitUemk5cEZvcDQK/sqWiwW+gbnehB03zQqUjpkQdo5hASef
            TH8Eak/zm2M+ktwAFEQAKemJOnhL2dFj8nStKJtjEi+OK9dvjIILzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T07:08:43Z"
    mac: ENC[AES256_GCM,data:TUdFV5hr7GeECFfTJjfIJcUwE3PO0UI+S5UCxslsujGZqkv5rWVTs6KxQ5Tf90Dq4aWykaspa13ei3WqjCVLkA7eFQvBjET4qRT5mCuWUcc8j8/r0AVfIt6RsMjkZokmBX6+jnx+cJqkqGIGPI87VTtotbyJSG1w4SJirZmm8uw=,iv:iGOVRST/XdNtI3eMaSlbRk/XQmAYlaoIojwB7zWjufY=,tag:Dm0XXbywDRYq0PL8CIf4FA==,type:str]
    version: 3.13.3
