apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: ghcr-pull
    namespace: tbd-staging
data:
    .dockerconfigjson: ENC[AES256_GCM,data:alvJqh8uyA+UC+GDelLt/5zhx0Sg9+dJRMuFPLsMDZY6swYx51XAFLUeh9AQiiqKL8EmJ2b/QL2DCf/NINEORMaTvWPAdINX3wZpq2acdKXCiG4/2XLmEP++GhZPNf0TpT8qK8cvbdu1q+1W6hJ/6JdRuQUDDa6F0LVx6eGS4JhaW9j/NBhz+w==,iv:LbkacVZgPsmWRUP7DqMPuo0i/xWWV5SKU1C2TXw5nKU=,tag:QohrQvdYxjLSp2xWoad8pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdW5yVUtSZ1pKRCtGN0JM
            cEhFZDErUDk4dGVkVlZJUHVtZkZPVGlrdUVZCmlVem1EUVVVMU1zMzhBNFFKR1RZ
            THdMWjhlM0ZpRGE4L3hCcFNZcXp3M1kKLS0tIFFKczFXWC9taHVUU2kyOVIrZGI4
            b0VZUEpLTnY0U3ZmOWRTNDViRXhRZE0KRxafssLvbQpTNH7q1kFcLOeunwStgER0
            JXU/UQgXSTyQKT2WaRk0uwVYQa3uQbkcWUE7UXQQSwrJ4+f2sWMl6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T19:09:17Z"
    mac: ENC[AES256_GCM,data:8l1aOigorrYfhx4rFl2bEtQehbHZvn0kmW3zCuOiaoyCJGk40zhODalMAseop9VL5cd6EYHfoXyRfnFMakd7MAaBR/ZvA8DcEOsIoNdK/bFO5MJEIr0e4QYSHRi0nA4SgR0ZNbCfjJX6WtCjaTjfO0wdof/XEpa/LpYpNPx9Ils=,iv:V2WSg+yUf9cdhwY1win15Ox9Hg7c+kgNg1pg7zA5yj0=,tag:0GEGj9ZjUt88QpLHYEcGjA==,type:str]
    version: 3.13.3
