apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:74Ty7R3rPiZCs4zCYYquBp0yVplLIWIP1bBDeV184ApjOmI4Bdt16x0Fv0yon7usV3cX+Q63rQwZQnT91ffWGzh+UJuB1TfBmd8btZWc6hqOeZTiRc3cjXfL5DbQcy/43gqpxJYHYjADIQ9xoNsA6XjyKGGR658hOe4WaBiVRHQlzdMxaIA7mw==,iv:R7XaV9iKS9m0CiYIGqFNV/8+9hLdoPt355489u/Y9sU=,tag:XHdKSGVMK6x0+Z4fk1N0cg==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: tbd-prod
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByd3FxTlBXK3R3dFo0ckN3
            RzFscHdteWoxSktRWGIvb0hHMXA3ZVA0NDNJClNueWRSWm42d0g4MWYxaFFheHFO
            bGord0ZPN3IzZDJ0OFd1VWdlOEx2ek0KLS0tIFVWZUpsODVmazI3d2NWbGZnbmhY
            blRicHRjeXN5aExFeXFzNXl2RGN0OG8KkKvGa0p9CdRgIxN0RrRyNTcB6T3fQCVI
            vE4GvugtDbOUymgRpEc7rSiH9OXpD0YgRAsOaMd5CYy7kwEjWgcBGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T14:32:53Z"
    mac: ENC[AES256_GCM,data:/HUVegvkGff9ctJwRQTq9nqUt5l1FMhB6iXL7i2bm1ObJKHMFqAB6HJc2BHDvr/yMzQdvU7VvLyyY50Pc9DQd7CUzEi4KkOrCg1zic9PRvrsyjF4iOEugSB72Ylx6ipjzCgMxXvvtWsjSIsmL3Y5gQkXEt35R4WGL3CVnoA8wzI=,iv:gAKVWKjIYK3r0rWaEu9iTvQNYH0Igj6Ew0ITXx22sts=,tag:/jxhUcNPx8zZDemX0zwnHQ==,type:str]
    version: 3.13.3
