apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:8UlkS+xpiksdVmb4sCApfai7Fv0k/kpr5s6PHhj5Li/8MhQfWm6FBnj8KdPXoNbAAWQtF1S/ZGgcwdhbDFZ3o+vnK452swNn4DWkbb065wnK8ZfjGKvTS9127H7WPyjDCD3ZZMxtGrs7lZWSVAr3LT8uLk6VgNIbplAwR8wuvwIGv5XInJ43SA==,iv:8KPB3qn7QzyCBvTBtU7AxN5ZQyoG4aoQZiXXSvfn88I=,tag:fLua9OiuTE3o9mOWfnav5Q==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: ziftbook-staging
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYll3L2ZpWnNQT01IMHpM
            a09xYzh2UXJEQ096bmdxbVZ3MSt0M0lDZGxjCnZiT1czTFJSRC9vVEUzRjRDbGZp
            Q2orNGJ4YldCTGNhVjhzUkcvOGo0SjgKLS0tIC9aTkFxYVk2cWd6aXZDbm81RjFH
            T25DNEpOOVMvZy95WkY0bWQ5S3JVcDQKcMGwNlE9oWSBKZSh6UPEaJMxwK9HXZ0W
            KwZHfpCVmeCmq7I1AKxR947QmDsc8v9YTT3kUW+5tviAxl0wuhIwGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T14:32:53Z"
    mac: ENC[AES256_GCM,data:lXGRcaLKjvTernaRp4AHQ2E4bZHcOUnbToH7icloI/hVh+seyTi+HtoI54+KJrpeVxphymLhkDAp5+5/WPjiIeGy3aVJ4JSbeII2/u4PccmBJApKRKVRZlbsxMz/C3FqWVtKywlq5GWVNKujA9+70X9kVuXk+bg9hJVBRqEvd6s=,iv:1irZO4/k3YHB3TnOVY2W3a92kQQ61OPTGdmQpEnfS5c=,tag:oHGD48CZxzz2RB0fAB6+iA==,type:str]
    version: 3.13.3
