apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: ghcr-pull
    namespace: ziftbook-prod
data:
    .dockerconfigjson: ENC[AES256_GCM,data:GA60xqjXg1bE7PzKQl6GSFzv5ELrXrvUKHN2vA7pKG1CCzFFo/udYbn8nWWpLoNXxZqWV0XTOYB7UbslLqa0BAtGTf1UusrmKNcnc4BHbgdVSi/nK1VRwqpx9um5VddnoPnhhPpCAyYTBJrtAmtHgypkbsgVKK6KMznoGTfZV556vgi7I9aTdg==,iv:OGVZJW3chIrMvJl65x1Rf24be5dB+ucZFcSN8Zn8L9s=,tag:+whNe6DRNTbxvxbaGmXWpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TjMxbGpSc2VWaStXWEV1
            N1U0Nnpha3VHcEZ5clZWTytQaXNDKzlEVUNBCm4yWHI2VXlBUzllVnNDbGZ0eDJt
            RVRIVEF6NjVMSzBGWTl4WnFjRlB1VU0KLS0tIERocENZT3JocjhLZ0ZONE5MSjNo
            OWtPMitYenJsbjRYQUJVTzZ2VTFaWWMKrehDAoNVr/E+/+KIQZa1dpWruHJZxvli
            CpZNUKipFkAUegP3BuJUmvTI2HSUXpyDrKZY1ZjfnMmWg1qLc+RCzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e7q279sydk4n4kvpgldzadq3e9r9det9tnrnv33kyk9wdlq47vvsvd3wap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T17:08:22Z"
    mac: ENC[AES256_GCM,data:SJTzVorvk3wWQUOZOo2ndh5fmhws86AkqY8c4rmaXPn8Spvgv6xhKmD5u0R0K23/YH/OmiiPawB4Kr4QpW2ne2l2UJzkpOdgC4o7MbCoRqCOP6nx82yc4Rv+0qPxZ7yEAhnT9t4a9XJ7AcsDcIyG2N5kfBOFBXtaCsLAyQZVNOs=,iv:4ztC6ckt2sYWo7GsdZ7JElzZyylegIkyyMh7MU8Z9gI=,tag:axxg0D9RdNMXcKD1XKGtYA==,type:str]
    version: 3.13.3
